sudo: required
services:
  - docker
before_install:
  - docker build -t jsaul3/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true jsaul3/docker-react npm run test
deploy:
  provider: elasticbeanstalk
  region: "ap-souteast-2"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-879381260218"
  bucket_path: "frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
